### ISSUE TITLE
[Devmon]--exec-on-XXX ignored by mounts on daemon startup

### ISSUE THREAD

**Issue by Garandor** [IgnorantGuru/udevil#48]
I am trying to use Devmon (started by systemd on ArchlinuxARM(RasPi)) to automatically start services on mount of an external USB drive. This drive is usually plugged in at boot, causing devmon to ignore the --exec-on-label statement.
Replugging the drive when the devmon daemon is already running results in the script getting executed.

Is this intended behaviour?
If yes, would it be possible to add an option to also execute on initial mounts caused by the devmon daemon starting up?

cat /etc/conf.d/devmon
ARGS="--exec-on-label Anystore /home/pi/scripts/on_mount.sh"

**Comment by DBMandrake** [comment]
I would like to add an additional voice asking for a command line option to enable always running --exec-on scripts, even for drives mounted during devmon startup and not just those hot plugged after devmon has already started.

We are working on switching OSMC from udisks1/udisks-glue to udevil/devmon as the automounter system and this is one of the sticking points for us being able to make this change. While we can no doubt customise devmon to do this ourselves that means maintaining our own downstream version of the script (probably using a dpkg divert) which is not ideal since we would not automatically keep up to date with bug fixes and new versions of the script.

In our use case there is no X desktop and no concept of a GUI "user login", the system boots directly to Kodi and devmon would be run automatically as a systemd service during startup. We have a number of uses for the --exec-on scripts including adding and removing samba user shares (net usershare add, net usershare delete) automatically when drives are connected and disconnected to add and remove shares on the fly.

If the script to add shares does not run on drives that are already connected during boot they will not get a samba share added, while those that are plugged in after booting would. The automounter is not just used by our users for transient drives like thumb drives, it is typically used for permanently connected USB spinning drives as well to allow the drive to "just work" (including adding a samba share) without requiring a user to delve into /etc/fstab.

Although it doesn't always make sense to run mount scripts on boot ours is definitely a use case where it does.

**Comment by IgnorantGuru** [comment]
An --always-exec universal option has been added for this in [devmon 1.1.9](https://raw.githubusercontent.com/IgnorantGuru/udevil/6ac69ed255626192758ee851594928498d9c10de/src/devmon) (due for release with udevil 0.4.5), which will cause exec commands to run during startup or when performing --mount-all.  Please see how that works for you.  See BUILD  NEXT in README for testing.

**Comment by tkarls** [comment]
I too love this feature. As the OP I use a raspberry pi as a standalone "headless server". Thus I want the same thing happening when user plugs in a USB drive after boot as if a USB drive is plugged in and user power cycles the device.

Glad to see it fixed. Although, when can this be expected to be released. I can see that 0.4.5 has no date set. May I humbly suggest to make a release of what is fixed now and push the other items into a  0.4.6 release?
