### ISSUE TITLE
devmon: let users customize default mount option

### ISSUE THREAD

**Issue by cykerway** [IgnorantGuru/udevil#58]
devmon has a default mount option:

defaultmountoptions="noexec,nosuid,nodev,noatime"

The consequence is that if I want to use "relatime" then I have to manually specify "--mount-options relatime" every time I mount a device. 

I know it's a shell script so that it's easy to edit it in place. However, editing a binary doesn't seem to be a good idea in general if you consider it's managed by a package manager in a Linux distro. Editing a configuration file is better, but I only see one for udevil, not devmon (for a manual run, not via systemd).

**Comment by IgnorantGuru** [comment]
devmon is a configurationless script.  If you're running it from the command line, one good approach for this is to define an alias.  For example if you enter in a bash shell:

```
alias devmon="devmon --mount-options=noexec,nosuid,nodev,relatime"
```

Then you can just enter 'devmon' to run it.  You can make this alias persistent by adding it to your shell's init script, such as ~/.bashrc.

Another approach is to install a script on your system that runs devmon with the options you want, so you just run your script - similar to an alias but lets you do more.

And another is to install a modified version of devmon to /usr/local/bin.  In this way it will take precedence when you run it (see 'which -a devmon'), yet won't modify the copy installed by your package manager.  devmon is just a bash script, and it's not updated very often, so easy to maintain.

Finally, you might also note that you can run udevil directly - that's all devmon's client mode does.  So just run 'udevil mount /dev/...' instead of devmon.  That way you have fine-grained control of the default options via udevil.conf.  I think that's the simplest solution.
