### ISSUE TITLE
How to get notifications? 

### ISSUE THREAD

**Issue by spectromas** [IgnorantGuru/udevil#60]
I've reinstalled udevil today and noticed that portage told me that zenity is an optional dependency to get notifications. I can't find any information on how to set this up though, I have zenity, udevil and spacefm installed but I get no notifications. I did see a devmon initscript linked here but that didn't make much difference.

**Comment by IgnorantGuru** [comment]
zenity (or spacefm) can be used with devmon to produce pop-up messages, such as showing when devices are being unmounted or if there is an error.  You can run <code>devmon --help</code> and note the "popup" references for some functions.

If you have spacefm installed, it will use SpaceFM Dialog to show the popups instead of zenity iirc.
